/** 🌹oddFEELING */

import Head from 'next/head';
import Script from 'next/script';
import React, { useRef } from 'react';
import NavLayout from '../layout/nav.layout';
import parseLogic from '../logic/parse.logic';
import { dataStore } from '../global/data.global';
import ActionCard from '../components/actionCard.component';
import IndicatorComponent from '../components/Indicator.component';
import StageComponent from '../components/homeComponents/Stage.component';

// ======= component imports -->
import {
  Main,
  Container,
  HelperSection,
  ImportWrapper,
  TextPaste,
} from '../styles/Home.component';

export default function Home() {
  const csv_inp_ref = useRef();
  const json_inp_ref = useRef();
  const { type, setType, setData, setFields } = dataStore((state) => state);

  // ======= pick file-->
  const csvPicker = () => {
    csv_inp_ref.current.click();
    setType('csv');
  };
  const jsonPicker = () => {
    json_inp_ref.current.click();
    setType('json');
  };

  // ======= set file -->
  const setFile = (event) => {
    const reader = new FileReader();
    reader.readAsText(event.target.files[0]);
    reader.onload = (event) => {
      if (type === 'csv') {
        const parsed = parseLogic.PARSE_CSV(event.target.result);
        setData(parsed.data);
        setFields(parsed.meta.fields);
      }
    };
  };

  return (
    <Container>
      <Head>
        <title>Dataphrappper</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Main>
        <HelperSection>
          <IndicatorComponent step={1} details='Import data' />

          <ImportWrapper>
            <ActionCard
              onClick={csvPicker}
              icon='eos-icons:csv-file'
              text='Upload CSV'
            >
              <input
                onChange={setFile}
                type='file'
                accept='.csv'
                style={{ display: 'none' }}
                ref={csv_inp_ref}
              />
            </ActionCard>

            <ActionCard
              onClick={jsonPicker}
              icon='codicon:json'
              text='Upload JSON'
            >
              <input
                type='file'
                onChange={setFile}
                accept='.json'
                style={{ display: 'none' }}
                ref={json_inp_ref}
              />
            </ActionCard>

            <ActionCard
              icon='akar-icons:link-chain'
              text='Download Link'
            ></ActionCard>
          </ImportWrapper>

          <TextPaste placeholder='Paste CSV formatted data here' />
        </HelperSection>

        {/* ====== Stage section */}
        <StageComponent />
      </Main>

      <Script src='https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js' />
    </Container>
  );
}

//=============================================>  layout
Home.getLayout = function getLayout(page) {
  return (
    <NavLayout>
      <>{page}</>
    </NavLayout>
  );
};
